/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ftp.ltm;

import java.awt.List;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.LinkedHashMap;
import java.util.Scanner;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class FTPclientFrom extends javax.swing.JFrame {

    private static Socket socket = null;
    private static DataInputStream din = null;
    private static DataOutputStream dout = null;
    public static String username;
    private static LinkedHashMap<String, String> mapQuyenUser = null;

    /**
     * Creates new form client
     */
    public FTPclientFrom(String username, Socket socket) throws IOException, ClassNotFoundException {
        initComponents();
        this.username = username;
        this.socket = socket;
        start(socket);

        loadDir(username, list_file_user);
        loadDir("chung", list_file_chung);
    }

    public void start(Socket socket) {
        try {
            din = new DataInputStream(socket.getInputStream());
            dout = new DataOutputStream(socket.getOutputStream());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Chưa mở server");
        }

        System.out.println(username);
    }

    private void loadDir(String username, java.awt.List list) throws IOException {
        list.clear();
        dout.writeUTF("reload");
        dout.flush();
        dout.writeUTF(username);
        dout.flush();
        String listFile = din.readUTF();
        StringTokenizer st = new StringTokenizer(listFile, ":");
        while (st.hasMoreElements()) {
            list.add(st.nextToken());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtext_file = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton_Browse = new javax.swing.JButton();
        jButton_receiveFile_C = new javax.swing.JButton();
        btGui = new javax.swing.JButton();
        list_file_user = new java.awt.List();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        list_file_chung = new java.awt.List();
        jCheckBox_chung = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Client");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setText("Select file");

        jButton_Browse.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton_Browse.setText("Browse");
        jButton_Browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BrowseActionPerformed(evt);
            }
        });

        jButton_receiveFile_C.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton_receiveFile_C.setText("Receive");
        jButton_receiveFile_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_receiveFile_CActionPerformed(evt);
            }
        });

        btGui.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        btGui.setText("Send");
        btGui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuiActionPerformed(evt);
            }
        });

        list_file_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_file_userActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setText("Thư mục của user");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel4.setText("Thư mục chung");

        list_file_chung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_file_chungActionPerformed(evt);
            }
        });

        jCheckBox_chung.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jCheckBox_chung.setText("File chung");

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton1.setText("Reload");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(list_file_user, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(list_file_chung, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jtext_file, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Browse))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_receiveFile_C)
                                .addGap(36, 36, 36)
                                .addComponent(btGui)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox_chung)
                                .addGap(68, 68, 68)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtext_file, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton_Browse))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGui)
                    .addComponent(jCheckBox_chung)
                    .addComponent(jButton_receiveFile_C)
                    .addComponent(jButton1))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(list_file_chung, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(list_file_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuiActionPerformed
        // TODO add your handling code here:

        if (jtext_file.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập tên file");
        } else {
            try {
                sendFile();
            } catch (Exception ex) {
                Logger.getLogger(FTPclientFrom.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_btGuiActionPerformed

    private void jButton_BrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(jButton_Browse);

        jtext_file.setText(chooser.getSelectedFile().getAbsolutePath());

    }//GEN-LAST:event_jButton_BrowseActionPerformed

    private void jButton_receiveFile_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_receiveFile_CActionPerformed
        String nameFile = jtext_file.getText();

        if (nameFile.equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập tên file");
        } else {
            try {
                receiveFile(nameFile);
            } catch (Exception ex) {
                Logger.getLogger(FTPclientFrom.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_jButton_receiveFile_CActionPerformed

    private void list_file_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_file_userActionPerformed
        jtext_file.setText(list_file_user.getSelectedItem());
        jCheckBox_chung.setSelected(false);
    }//GEN-LAST:event_list_file_userActionPerformed

    private void list_file_chungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_file_chungActionPerformed
        jtext_file.setText(list_file_chung.getSelectedItem());
        jCheckBox_chung.setSelected(true);
    }//GEN-LAST:event_list_file_chungActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            loadDir(username, list_file_user);
            loadDir("chung", list_file_chung);
        } catch (IOException ex) {
            Logger.getLogger(FTPclientFrom.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FTPclientFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FTPclientFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FTPclientFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FTPclientFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FTPclientFrom(username, socket).setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(FTPclientFrom.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(FTPclientFrom.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

    }

    public void sendFile() throws FileNotFoundException {
        String urlFile = jtext_file.getText();
        System.out.println(urlFile);
        File file = new File(urlFile);
        if (!file.exists()) {

            JOptionPane.showMessageDialog(this, "File not Exists...");
        } else {
            try {
                dout.writeUTF("send");
                dout.flush();
                dout.writeUTF(username);
                dout.flush();
                String message = din.readUTF();
                if (message.equals("UP")) {
                    if (jCheckBox_chung.isSelected()) {
                        dout.writeUTF("chung");
                        dout.flush();

                    } else {
                        dout.writeUTF(username);
                        dout.flush();
                    }
                    message = din.readUTF();
                    System.out.println(message);
                    if (message.equals("UPdirchung")) {

                        dout.writeUTF(String.valueOf(file.length()));
                        dout.flush();
                        message = din.readUTF();
                        if (!message.equals("ok")) {
                            JOptionPane.showMessageDialog(this, message);
                        } else {
                            dout.writeUTF(urlFile);
                            dout.flush();
                            FileInputStream fin = new FileInputStream(file);
                            int ch;
                            do {
                                ch = fin.read();
                                dout.writeUTF(String.valueOf(ch));
                            } while (ch != -1);
                            fin.close();
                            JOptionPane.showMessageDialog(this, "Send File success ");
                            loadDir(username, list_file_user);
                            loadDir("chung", list_file_chung);
                        }
                    } else if (message.equals("UPdir")) {

                        dout.writeUTF(String.valueOf(file.length()));
                        dout.flush();
                        message = din.readUTF();
                        if (!message.equals("ok")) {
                            JOptionPane.showMessageDialog(this, message);
                        } else {
                            dout.writeUTF(urlFile);
                            dout.flush();
                            FileInputStream fin = new FileInputStream(file);
                            int ch;
                            do {
                                ch = fin.read();
                                dout.writeUTF(String.valueOf(ch));
                            } while (ch != -1);
                            fin.close();
                            JOptionPane.showMessageDialog(this, "Send File success ");
                            loadDir(username, list_file_user);
                            loadDir("chung", list_file_chung);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Bạn đã bị block UP dir này ");
                    }

                } else if (message.equals("blockUP")) {
                    JOptionPane.showMessageDialog(this, "Bạn đã bị block UP");
                }

            } catch (FileNotFoundException ex) {
                Logger.getLogger(FTPclientFrom.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(FTPclientFrom.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }

    public void receiveFile(String nameFile) {
        try {

            dout.writeUTF("receive");
            dout.flush();
            dout.writeUTF(username);
            dout.flush();
            String message = din.readUTF();
            if (message.equals("down")) {
                if (jCheckBox_chung.isSelected()) {
                    dout.writeUTF("chung");
                    dout.flush();
                } else {
                    dout.writeUTF(username);
                    dout.flush();
                }
                message = din.readUTF();
                if (message.equals("DOWdir")) {
                    dout.writeUTF(nameFile);
                    dout.flush();

                    message = din.readUTF();
                    if (message.equals("File not Exists")) {
                        JOptionPane.showMessageDialog(this, "Server : file không tồn tại");
                    } else if (message.equals("File Exists")) {
                        message = din.readUTF();
                        if (message.equals("ok")) {
                            File dir = new File("D://FTP_receive");
                            if (dir.mkdir()) {
                                System.out.println("Create directory " + dir.getAbsolutePath() + " success.");
                            }
                            File f = new File("D://FTP_receive//" + nameFile);
                            FileOutputStream fout = new FileOutputStream(f);
                            int ch;
                            String temp;
                            do {
                                temp = din.readUTF();
                                ch = Integer.parseInt(temp);
                                if (ch != -1) {
                                    fout.write(ch);
                                }
                            } while (ch != -1);
                            fout.close();
                            JOptionPane.showMessageDialog(this, "Nhận file thành công\n File tải về nằm ở\n\tD:/FTP_receive");
                            // System.out.println("Đã nhận");
                        } else {
                            JOptionPane.showMessageDialog(this, "file lớn hơn giới hạn không thể tải về ");

                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Bạn đã bị block DOWN dir này ");
                }

            } else if (message.equals("blockdown")) {
                JOptionPane.showMessageDialog(this, "Bạn đã bị block Down");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Nhận file thất bại, server lỗi");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGui;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Browse;
    private javax.swing.JButton jButton_receiveFile_C;
    private javax.swing.JCheckBox jCheckBox_chung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtext_file;
    private java.awt.List list_file_chung;
    private java.awt.List list_file_user;
    // End of variables declaration//GEN-END:variables

}
